### ISSUE TITLE
Proper argparse support

### ISSUE THREAD

**Issue by alex-phillips** [alex-phillips/plex-autocollections#10]

**Comment by alessandrojcm** [comment]
I could tackle this, tough I would recommend using [Click](https://click.palletsprojects.com/en/7.x/) instead of argparse.

**Comment by alex-phillips** [comment]
Whatever works! I'm not too picky.

**Comment by alessandrojcm** [comment]
Cool, could you please assign the issue to me? 

⁣Enviado desde BlueMail ​

**Comment by alex-phillips** [comment]
Weird, for some reason it won't let me assign to anyone but myself...

**Comment by alessandrojcm** [comment]
You have to add me to the repo first. 

⁣Enviado desde BlueMail ​

**Comment by alessandrojcm** [comment]
So I've finally had the chance to take a look to implement this; but it's not clear to me where you want cli support. As far as I can tell, the app prompts you for username/password and then does it's thing until it is done, or until it prompts for selection. Could you please elaborate on where do you want cli support?
