### ISSUE TITLE
Use config file

### ISSUE THREAD

**Issue by alex-phillips** [alex-phillips/plex-autocollections#11]

**Comment by mbarakaja** [comment]
Do you mean **`ini-like`** config files? Such as setup.cfg?

**Comment by alex-phillips** [comment]
Sure. Maybe something like I ended up doing here? https://github.com/alex-phillips/piwigo-cli

Would just be nice not to have to type in a username and password every time.

**Comment by alex-phillips** [comment]
Was referring to the config in this file specifically https://github.com/alex-phillips/piwigo-cli/blob/master/piwigo/cli.py

But I'm not picky

**Comment by mbarakaja** [comment]
Ok, I will give it a try this week. [**`ConfigParser`**](https://docs.python.org/3.6/library/configparser.html) from the standard library is pretty good for this case.

**Comment by alex-phillips** [comment]
closed - used built-in config support that comes with plexapi package
