### ISSUE TITLE
A suggestion, which I'm happy to turn into a PR

### ISSUE THREAD

**Issue by aram535** [alex-phillips/plex-autocollections#34]
Thank you for this ... I had a rather large script to do build these since I had to rebuild my database a couple of times after I had moved or had to reimport everything.  Very nicely done. 

If I may make a suggestion on the collections.yml file ... you're better off doing digital matching rather than actual versions ... it'll be a bit quicker (I think is most cases although I'm no Python expert) and it'll be less updates in the future.   There are a bunch of instances of this, and I can make it a PR if you like - figured I would ask first.

Example:

Toy Story:
  - ^Toy Story( [0-3])?$

Can be: 
  - ^Toy Story( [\d{1}])?$

So 4-9 are also covered ... which would save a change+commit of "4" in there since Toy Story 4 is out.

**Comment by alex-phillips** [comment]
@aram535 That's a great point. I'd be happy to accept a PR and any future collections I add I'll use digital matching instead of specific numbers. Thanks!
