### ISSUE TITLE
Provide section index / indices as a parameter

### ISSUE THREAD

**Issue by shoopdawoop** [alex-phillips/plex-autocollections#42]
I would like to run the script periodically via cron, is there a way to prevent it asking for the section index to work on and provide that as a parameter instead?

If not, please consider this a fesature request :)

**Comment by tomhoover** [comment]
@shoopdawoop, Great idea! I'm busy with Mother's Day stuff today, but give me a week and I'll get a PR submitted to @alex-phillips.

**Comment by shoopdawoop** [comment]
> @shoopdawoop, Great idea! I'm busy with Mother's Day stuff today, but give me a week and I'll get a PR submitted to @alex-phillips.

@tomhoover @alex-phillips I've only just gotten around to setting this up and it works great. Thank you guys!
