### ISSUE TITLE
[Bug?] - adding multiple unrelated movies to the collection.

### ISSUE THREAD

**Issue by DevXen** [alex-phillips/plex-autocollections#44]
when i just put:

```
Saw Films:
  - Saw

```

In the yml file. it adds all the following to the collection:

Adding CHAINSAW MAID to collection Saw
Adding Hacksaw Ridge to collection Saw
Adding Harvesters Texas Chainsaw Massacre Spin Off to collection Saw
Adding Hollywood Chainsaw Hookers to collection Saw
Adding I Saw the Light to collection Saw
Adding Jigsaw to collection Saw
Adding Leatherface: The Texas Chainsaw Massacre III to collection Saw
Adding Saw to collection Saw
Adding Saw 3D to collection Saw
Adding Saw II to collection Saw
Adding Saw III to collection Saw
Adding Saw IV to collection Saw
Adding Saw V to collection Saw
Adding Saw VI to collection Saw
Adding The Texas Chain Saw Massacre to collection Saw
Adding The Texas Chainsaw Massacre to collection Saw
Adding The Texas Chainsaw Massacre 2 the Gruesome Edition to collection Saw
Adding The Texas Chainsaw Massacre: The Beginning to collection Saw
Adding Texas Chainsaw Massacre: The Next Generation to collection Saw
Adding VeggieTales: Tomato Sawyer & Huckleberry Larry's Big River Rescue to collection Saw
Adding Velvet Buzzsaw to collection Saw

Sure I can narrow that down by adding a year. but that only works if none of the other movies came out during the same year.  So that doesn't seem like an option.

is there something else i might be able to do to prevent that from happening? - It was my understanding that it would only pull absolute matches, not relative matches.

Thanks,
-Dev

**Comment by alex-phillips** [comment]
This works via regular expressions. If you look how this specific movie is currently handled (Saw), you'll notice that it is ONLY checking for movies with the exact name `Saw`: https://github.com/alex-phillips/plex-autocollections/blob/master/collections.yml#L191

So if this is something you added to your collection yourself, try narrowing down the regular expression instead of by year.

**Comment by DevXen** [comment]
Yeah so. I wasn't using regular expressions. (I suck with them anyways.) I'm my testing I created a yaml file that only had:

Saw Films:
  - Saw

In it.

I and in had temporary renamed collections.yml so it wouldn't be using any of those. (For testing.)

Though looking at that file I can see that there is regular expressions on the just the word saw to pull up only that movie. Then the sequels after that. So I guess I can just add: ^ to the beginning and $ to the end to limit words/titles as needed so it doesn't pull up everything with said word/title in it. Not a great solution.. But I think I can manage with doing that. Haha.

Thank you.
